CREATE PROCEDURE [CRMLite].[CreatePayPalStatistic] @ID UNIQUEIDENTIFIER,
	@LeadID UNIQUEIDENTIFIER,
	@first_name NVARCHAR(50),
	@last_name NVARCHAR(50),
	@email NVARCHAR(50),
	@total NVARCHAR(50),
	@currency NVARCHAR(50),
	@city NVARCHAR(50),
	@state NVARCHAR(50),
	@postal_code NVARCHAR(50),
	@country_code NVARCHAR(50),
	@intent NVARCHAR(50),
	@create_time DATETIME,
	@payment_mode NVARCHAR(50),
	@recipient_name NVARCHAR(50)
AS
INSERT INTO [CRMLite].[PayPalStatistic] (
	ID,
	LeadID,
	first_name,
	last_name,
	email,
	total,
	currency,
	city,
	[state],
	postal_code,
	country_code,
	intent,
	create_time,
	payment_mode,
	recipient_name
	)
VALUES (
	@ID,
	@LeadID,
	@first_name,
	@last_name,
	@email,
	@total,
	@currency,
	@city,
	@state,
	@postal_code,
	@country_code,
	@intent,
	@create_time,
	@payment_mode,
	@recipient_name
	)
