CREATE TABLE [CRMLite].[Currency] (
    [ID]   TINYINT      NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    CONSTRAINT [PK_CURRENCY] PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([Name] ASC)
);