CREATE TABLE [CRMLite].[Currencies] (
    [ID]   INT      NOT NULL IDENTITY(1,1),
    [Code] NVARCHAR(50) NOT NULL, 
    [Title] NVARCHAR(255) NOT NULL,
    CONSTRAINT [PK_CURRENCY] PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([Title] ASC)
);