CREATE TABLE [CRMLite].[OperationTypes] (
    [ID]   TINYINT IDENTITY   NOT NULL,
    [Type] NVARCHAR(50) NOT NULL,
    CONSTRAINT [PK_OPERATION_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([Type] ASC)
);